"""empty message

Revision ID: 298275443219
Revises: 
Create Date: 2021-04-26 21:55:07.484877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298275443219'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('ingredient_id', sa.String(), nullable=False),
    sa.Column('measurement', sa.String(), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_stock_equivalent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('capacity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('capacity_equivalent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('capacity_measure', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ingredient_id')
    )
    op.create_table('menu',
    sa.Column('menu_item_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ingredients', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('menu_item_id')
    )
    op.create_table('restock_purchase',
    sa.Column('purchase_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.String(), nullable=False),
    sa.Column('purchase_type', sa.String(), nullable=False),
    sa.Column('items_purchased', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('restock_purchase')
    op.drop_table('menu')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
