"""empty message

Revision ID: 7dab363bceee
Revises: 629f15f5d829
Create Date: 2021-04-28 01:08:31.108514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dab363bceee'
down_revision = '629f15f5d829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients_in_progress',
    sa.Column('ingredient_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount_in_progress', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_in_progress_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ingredient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredients_in_progress')
    # ### end Alembic commands ###
